- name: Demostrar módulos K8s
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    namespace:
    
  module_defaults:
    group/k8s:
      namespace: "{{ namespace }}"
      api_key: ""
      host:
      
  tasks:
    - name: Crear los objetos del manifiesto
      k8s:
        state: present
        src : "{{ playbook_dir + '/hello.yml' }}"
        
    - name: Cambiar de ClusterIP a NodePort
      k8s_service:
        state: present
        name: nodejs-ex
        type: NodePort
        ports:
          - port: 8080
            protocol: TCP
            
     - name: Obtener indoramción de los pods
       
            
      
      
    
